#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

find . -name ".*" -o -name "*.bash" | \
    grep -v .git$ | \
        sed 's/^.\///g' | \
            tail -n +2 | \
                xargs -I% rm $HOME/%

ls -al ~
