(add-to-list 'load-path "~/.emacs.d/settings")
(require 'packages)
(require 'general-settings)
(require 'window-settings)
(require 'clojure-settings)
(require 'python-settings)
(require 'python-flake8)
(require 'persian-settings)
(require 'dirtree-settings)
(require 'ruby-settings)
